added nemo_config parameter to nemo_prelude and build-nemo

diff --git a/lib/nemo_prelude b/lib/nemo_prelude
--- a/lib/nemo_prelude
+++ b/lib/nemo_prelude
@@ -4,14 +4,46 @@
 
 echo "#################### Start NEMO pre-processing #################"
 
+  stamp=`date "+%j%H%M%S"$$`
+
+  # this_host will simply be the output from uname
+  this_host=`uname -n|awk -F\. '{print \$1}' -`
+
+  # this_mach will be a known alias (or possibly the actual machine name)
+  this_mach=$this_host
+  ROUTE_SSH=''
+  case $this_mach in
+      c1*) this_mach=spica;  ROUTE_SSH='ssh spica'  ;;
+      c2*) this_mach=hadar;  ROUTE_SSH='ssh hadar'  ;;
+     ib3*) this_mach=pollux; ROUTE_SSH='ssh pollux' ;;
+   joule*) this_mach=joule;  ROUTE_SSH='ssh joule'  ;;
+  esac
+
+  # bail is a simple error exit routine
+  error_out="${JHOME:-$HOME}/.queue/error_nemo_processing_${runid}_${this_host}_$stamp"
+  [ -z "$error_out" ] || rm -f $error_out
+  bail_prefix="nemo prelude"
+  bail(){
+    echo `date`" $this_host $runid --- ${bail_prefix}: $*"
+    echo `date`" $this_host $runid --- ${bail_prefix}: $*" >>$error_out
+    [ -n "$model" ] && echo `date`" $this_host $runid --- ${bail_prefix}: $*" >>haltit
+    exit 1
+  }
+
 # Identify the location of the NEMO git repository and the commit within
 # that repository that is associated with the current run
   nemo_repo=${nemo_repo:=$CCRNSRC/ocean_dir/nemo-CCCma.git}
   nemo_ver=${nemo_ver:=''}
+  if [ -n "$nemo_ver" ]; then
+    # Dereference this commit and ensure we have a full sha1 hash
+    nemo_ver=`(cd $nemo_repo; git rev-parse $nemo_ver)` ||
+        bail "Unable to validate runtime nemo_ver"
+  fi
 
 # Identify the NEMO configuration associated with the current run
 # (e.g. CCC_ORCA1_LIM, CCC_ORCA1_LIM_CMOC, CCC_ORCA1_LIM_CANOE, ...)
   nemo_config=${nemo_config:=''}
+  export nemo_ver nemo_repo nemo_config
 
   echo "### NEMO runtime: nemo_repo   = $nemo_repo"
   echo "### NEMO runtime: nemo_ver    = $nemo_ver"
@@ -144,34 +176,6 @@ echo "#################### Start NEMO pre-processing #################"
   fi
 
   # Miscelaneous local definitions
-
-  # ---Start_submit_ignore_code----
-
-  stamp=`date "+%j%H%M%S"$$`
-
-  # this_host will simply be the output from uname
-  this_host=`uname -n|awk -F\. '{print \$1}' -`
-
-  # this_mach will be a known alias (or possibly the actual machine name)
-  this_mach=$this_host
-  ROUTE_SSH=''
-  case $this_mach in
-      c1*) this_mach=spica;  ROUTE_SSH='ssh spica'  ;;
-      c2*) this_mach=hadar;  ROUTE_SSH='ssh hadar'  ;;
-     ib3*) this_mach=pollux; ROUTE_SSH='ssh pollux' ;;
-   joule*) this_mach=joule;  ROUTE_SSH='ssh joule'  ;;
-  esac
-
-  # bail is a simple error exit routine
-  error_out="${JHOME:-$HOME}/.queue/error_nemo_processing_${runid}_${this_host}_$stamp"
-  [ -z "$error_out" ] || rm -f $error_out
-  bail_prefix="nemo prelude"
-  bail(){
-    echo `date`" $this_host $runid --- ${bail_prefix}: $*"
-    echo `date`" $this_host $runid --- ${bail_prefix}: $*" >>$error_out
-    [ -n "$model" ] && echo `date`" $this_host $runid --- ${bail_prefix}: $*" >>haltit
-    exit 1
-  }
 
   # Name a file to contain debugging info
   # This file will survive even when stdout goes missing
